01/05/2022, 20:35:46---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/05/2022, 21:27:12---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Forbidden (CSRF token missing or incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2520
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /clientes/delete/2/
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/clientes/views.py", line 69, in persons_delete
    person.delete(using='default')
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/db/models/base.py", line 953, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Person' because they are referenced through protected foreign keys: 'Venda.pessoa'.", {<Venda: 3- venda>})
"POST /clientes/delete/2/ HTTP/1.1" 500 96535
Not Found: /clientes/list/bootstrap-4.6.1/dist/css/bootstrap.min.css
"GET /clientes/list/bootstrap-4.6.1/dist/css/bootstrap.min.css HTTP/1.1" 404 6897
Not Found: /favicon.ico
01/07/2022, 07:47:46---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 07:48:30---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
01/07/2022, 08:00:22---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:01:55---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Internal Server Error: /produtos/list/
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/produtos/views.py", line 11, in produtos_list
    return render(request, 'produtos/produtos_list.html', {'produtos': produtos})
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'persons_update' with arguments '('',)' not found. 1 pattern(s) tried: ['clientes/update/(?P<id>[0-9]+)/$']
"GET /produtos/list/ HTTP/1.1" 500 187845
01/07/2022, 08:35:55---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:37:51---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:38:52---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:39:30---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:39:33---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:39:37---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:39:40---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:40:02---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:40:29---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:40:34---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:40:41---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:40:44---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:42:53---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:42:56---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:43:36---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
01/07/2022, 08:54:17---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 08:58:20---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
01/07/2022, 10:13:45---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5089
01/07/2022, 10:14:00---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:12:26---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 87, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:17:48---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:17:49---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:25---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:26---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:28---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:29---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:43---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:46---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:18:47---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:21:03---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 11:21:04---AnonymousUser
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 90, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
Not Found: /vendas/accounts/login/
"GET /vendas/accounts/login/?account_login=/vendas/ HTTP/1.1" 404 6637
01/07/2022, 11:56:44---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 12:41:37---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 16:05:55---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 20:27:32---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 20:27:38---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/07/2022, 20:27:44---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
Not Found: /favicon.ico
01/09/2022, 09:36:58---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:37:02---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:37:10---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:39:20---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:39:21---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:40:21---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:40:44---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
01/09/2022, 09:40:47---felipe
Traceback (most recent call last):
  File "/media/the_felipe/SSD ARQUIVOS/Env Django 3/Djnago_avancado/gestao_clientes/vendas/views.py", line 96, in get
    1/0
ZeroDivisionError: division by zero
